---
name: "hic-ubuntu-22.04-desktop-example"

base:
  name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server*"
  owner: "099720109477"

template:
  name: ubuntu

instance:
  # Use a large instance type to speed up the build process (smaller is fine for running)
  type: t3a.2xlarge
  volume_size: 30

modules:
  - autohibernate
  - conda-setup
  - libreoffice
  - pdfreader
  - rstudio
  - ssms
  - utils
  - vscode
  - shared-services-config

files:
  - src: conda-envs/example.yml
    dst: conda-environment.yml
