---
name: "hic-windows-nicedcv-example"

base:
  # E.g. DCV-Windows-2023.1.16388-DOD-78-2023-12-20T09-36-56.648Z
  name: "DCV-Windows-2023*-DOD-*"
  owner: "amazon"

template:
  name: windows

# subnet_id:

instance:
  type: t3.2xlarge
  volume_size: 50

env:
  - "AUTOHIBERNATE_TIME=120"

modules:
  - aws_ec2launch
  - 7zip
  - conda
  - dbeaver
  - firefox
  - libreoffice
  - notepad++
  - rstudio
  - ssms
  - vscode
  - autohibernate

files:
  - src: conda-envs/example.yml
    dst: conda-environment.yml
