# Useful GitHub Actions docs:

name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  # Check formatting
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          packer plugins install github.com/hashicorp/amazon

      - name: Run checks
        run: |
          make packer

  powershell_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Recursively run PowerShell checks
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Recurse -EnableExit -Path .

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run shellcheck on all modules
        run: |
          shellcheck modules/*.sh
